### PR TITLE
Fix goto/call/iwant stance exploit

### LINKED ISSUE #1222: Goto allows bypassing stance guards present in /load
When using `goto` or `call` when proned, stance of the other player isn't considered and you can wallstuck your head (load standing into a lower stance) or legs (load proned while facing away from a wall).

### PR DESCRIPTION
**Pull request by Aciz**
These commands bypassed typical save/load stance restrictions, which allowed for wallbugging.

fixes #1222

### CODE REVIEW

File: src/game/g_cmds.cpp [hunk 1]
```diff
@@ -4540,14 +4544,18 @@ void Cmd_Call_f(gentity_t *ent) {
     }
   }
 
+  Utilities::copyStanceFromClient(other, ent);
```
Comment (ovska) [inline src/game/g_cmds.cpp:4547]: These bits of `call` and `goto` code look identical, could maybe move to a common function such as `void MovePlayerToOther(gentity_t *player, gentity_t *other)`

**Review by ovska — APPROVED** [review]
