### PR TITLE
Runtimer fixes + refactoring

### LINKED ISSUE #1072: Checkpoint timer timestamps break at MAX_TIMERUN_CHECKPOINTS
After hitting 16th checkpoint, the timer displays `-00:00.001`, as this scenario isn't handled in code properly.

### PR DESCRIPTION
**Pull request by Aciz**
* Fix checkpoints not fading with runtimer
* Adjust runtime color transition range - no longer hardcoded, starts at the last 10% of the run (capped to 10s)
* Fix checkpoint Y coordinates not adjusting correctly on non-default checkpoint text size
* Refactoring
* Fix checkpoint timer breaking when hitting max checkpoints

Fixes #1072

### CODE REVIEW

**Comment by Aciz** [comment]
Should include fix for #1072 on this too.

**Comment by Aciz** [comment]
This should be ready now, checkpoint timer now correctly handles scenarios when player hits max timerun checkpoints.

File: src/cgame/etj_timerun_view.cpp [hunk 1]
```diff
@@ -211,128 +176,160 @@ void ETJump::TimerunView::draw() {
...
-        dir = "-";
       } else {
-        checkpointColor = &colorFail;
-        dir = "+";
+        bool isFasterCheckpoint;
+        // if we've hit max checkpoints, checkpointTime will be 0,
+        // so we need to compare currentTime against the comparisonTime,
+        // which will be previously set record in this scenario
+        if (maxCheckpointsHit) {
+          if (currentTime < comparisonTime) {
```
Comment (haapanen) [inline src/cgame/etj_timerun_view.cpp:223]: I guess this could just be isFasterCheckpoint = currentTime < comparisonTime;

File: src/cgame/etj_timerun_view.cpp [hunk 2]
```diff
@@ -211,128 +176,160 @@ void ETJump::TimerunView::draw() {
...
-      auto absoluteTime = checkpointTimeNotSet ? currentTime : checkpointTime;
+      const int absoluteTime = noCheckpointTimeSet || maxCheckpointsHit
+                                   ? currentTime
+                                   : checkpointTime;
 
       std::string timerStr = getTimerString(
           etj_checkpointsStyle.integer == 1 ? absoluteTime : relativeTime);
 
-      timerStr = dir + timerStr;
+      timerStr.insert(0, dir);
```
Comment (haapanen) [inline src/cgame/etj_timerun_view.cpp:253]: honestly this is less readable than dir + timerStr but 🤷

**Review by haapanen — APPROVED** [review]
